import { food } from "./app/shared/models/food"
import { Tag } from "./app/shared/models/tag"
export const sample_foods:food[]=[
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: '../../assets/food20.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch']
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: '../../assets/food19.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: '../../assets/food18.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: '../../assets/food16.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: '../../assets/food15.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: '../../assets/food14.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

 export const sample_tags:Tag[]=[
  {name:'All',count:6},
  {name:'FastFood',count:4},
  {name:'Pizza',count:2},
  {name:'Lunch',count:3},
  {name:'slowFood',count:2},
  {name:'Hamburger',count:1},
  {name:'Fry',count:1},
  {name:'soup',count:1},
]
